apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
secretGenerator:
  - name: pitpilot-secrets
    envs:
      - secret.example.env
images:
  - { name: pitpilot-api, newTag: latest }
  - { name: pitpilot-web, newTag: latest }
