apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - migrate-job.yaml
  - api.yaml
  - frontend.yaml
  - ingress.yaml
configMapGenerator:
  - name: pitpilot-migrations
    files:
      - migrations/0001_init.up.sql
      - migrations/0001_init.down.sql
